import path from "path"
import fs from "node:fs"
import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

/**
 * Path for build.
 * Connects to `test-vault` in `/test`
 */
const outdir = path.join("test", "test-vault", ".obsidian", "plugins", "obsidian-pert-estimate");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	// outfile: 'main.js',
	outdir: outdir,
	minify: prod,

	plugins: [
		{
			name: "copy-static",
			setup(build) {
				if (!fs.existsSync(outdir))
					fs.mkdirSync(outdir, { recursive: true });

				/* Copys `manifest.json` and `style.css` to outdir */
				fs.copyFileSync("manifest.json", path.join(outdir, "manifest.json"));
				if (fs.existsSync("style.css")) {
					fs.copyFileSync("style.css", path.join(outdir, "style.css"));
				}
			}
		}
	]
});


if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
